export const pilotLaunchChecklist = [
  "Restaurant profile is complete.",
  "Menu items are added and prices are correct.",
  "Delivery zones and fees are added.",
  "FAQs are added.",
  "Knowledge base policies are added.",
  "Brand kit is completed.",
  "Team members are invited and assigned roles.",
  "WhatsApp webhook is connected.",
  "Inbound WhatsApp message test passed.",
  "WHATSAPP_SEND_ENABLED is still false before final test.",
  "Test send works with trusted number.",
  "AI suggestions tested with real restaurant data.",
  "AI auto-reply is disabled until owner approves.",
  "Blocked AI safety test passed.",
  "Order flow test passed.",
  "Human takeover test passed.",
  "Reports/export tested.",
  "Pilot go-live approval is completed.",
];
